data:
  source: ibkr            # 'yahoo' | 'ibkr'
  store: parquet
  separate_roots: true
  root_dir_yahoo: data/eod/ETFs_yahoo
  root_dir_ibkr: data/eod/ETFs_ibkr
  calendar: US

trading:
  mode: paper             # 'paper' | 'live'

universe:
  tickers: [SPY, QQQ, DIA, IWM, XLK, XLF, XLE, XLV, XLY, XLP, XLI, XLRE, XLU, XLB, XLC]

pairs:
  rebalance_days: 21

risk: 
  capital: 500
  notional_per_trade: 120
  per_trade_pct: null
  max_pairs_open: 1
  daily_dd_stop_pct: 0.02

profiles:
  paper:
    risk:
      capital: 3000
      notional_per_trade: 500
      per_trade_pct: null
      max_pairs_open: 1
  live:
    risk:
      capital: 3000
      notional_per_trade: 500
      per_trade_pct: null
      max_pairs_open: 2

lookbacks:
  corr_days: 120
  coint_days: 120
  zscore_days_min: 12
  zscore_mult_half_life: 3.0

# #1
# selection:
#   min_corr: 0.6
#   max_half_life_days: 20
#   pval_coint: 0.05

# thresholds:
#   entry_z: 2.2
#   exit_z: 0.5
#   stop_z: 3.0
#   time_stop_days: 10

# #2
# selection:
#   min_corr: 0.55
#   max_half_life_days: 30
#   pval_coint: 0.10

# thresholds:
#   entry_z: 2.0
#   exit_z: 0.6
#   stop_z: 3.5

selection:
  min_corr: 0.6
  pval_coint: 0.05
  # max_half_life_days: 20

thresholds:
  entry_z: 2.5
  exit_z: 0.5
  stop_z: 3.5


stability:
  lookback_days: 120
  subwindows: 3
  min_pass_ratio: 0.67

decision:
  cool_off_bars: 5
  min_bars_between_entries: 10
  max_turnover_per_month: 8
  entry_require_cross: true
  entry_slope_confirm: true
  slope_lookback: 3

stats_filters:
  require_coint: true
  coint_pval_max: 0.05
  half_life_max_days: 20
  half_life_min_days: 2
  half_life_stability_tol: 0.20
  z_cap: 5.0
  beta_stability_tol: 0.20

market_filters:
  enable: true
  vix_path: data/eod/ETFs_yahoo/^VIX.parquet
  vix_max: 35
  macro_calendar_csv: config/macro_calendar.csv
  cool_off_hours: 2

quality:
  px_policy: best
  prefer_adj_close: true
  rebuild_adj_from_yahoo: true
  compare_adj_tolerance_bp: 50
  mask_ex_div: true
  mask_ex_div_days_after: 1
  min_volume: 1000000
  max_bidask_spread_bp: 20
  require_provenance_match: true

costs:
  commission_per_share: 0.005
  slippage_bp: 2

execution:
  ib:
    host: 127.0.0.1
    port_paper: 7497      # Paper trading (TWS Demo)
    port_live: 7496       # Live trading (TWS Live)
    client_id: 23
    allow_fractional: true

exports:
  topk: 20
  reports_dir: reports
  journals_dir: reports/journals
  decisions_csv: reports/decisions.csv
  orders_csv: reports/orders.csv

reports:
  pairs_scored_dir: reports/pairs_scored
